#!/usr/bin/env python3
"""Surgically patch ap/dp/mv in an already-committed map<N>_units.json in place.

export_units.py's full regeneration also drops native_treasure_event_rules,
native_record_class/race and death_effect/death_reward -- those are populated
by a separate later pipeline step this script does not know about (see
patch_units_hit_ev.py, which exists for the same reason). Re-running
export_units.py wholesale therefore silently regresses already-verified data.
This script instead loads the existing file byte-for-byte, recomputes only
ap/dp/mv via export_units.native_ap_for_raw_unit_key() /
native_dp_for_raw_unit_key() / native_mv_for_raw_unit_key(), and rewrites
just those three keys per unit -- every other key is left untouched.

Formula (full disasm of constructor 0x10d7f..0x10e23, function FUN_00010c50
body 0x10c50..0x11010, 2026-08-31 -- see the three functions' docstrings in
export_units.py for the complete evidence):
  - AP (record +0x37), DP (record +0x39): growth-table-byte * level on the
    high (enemy/friend, raw_unit_key>=0x44) branch, matching the already
    disasm-confirmed HP/MP shape; growth*level + a separate flat base word
    on the lower (persistent-style, raw_unit_key<0x44) branch -- NOT the
    same "+ growth*(level-1)" shape HP/MP's lower branch uses, confirmed
    directly from the pseudocode rather than assumed.
  - MV (record +0x3b): a flat per-(race,cls) value copied verbatim with NO
    level multiplication in either branch. The bug this fixes for MV is not
    missing level-scaling (there is none) but that the existing flat mv
    export came from a race/cls-mismatched table row (see export_units.py's
    PORTRAIT_CLS_NAME comment) rather than the raw-unit-key-indexed table
    the constructor actually reads.

Needs docs/data/exe_tables/native_unit_tables.json (generated by
extract_native_unit_tables.py) for the raw growth-table bytes, keyed by each
unit's own "portrait" field (== raw_unit_key, see export_units.py). Units
without proven native_constructor provenance (raw_unit_key outside the
extracted tables, or lv missing) are left untouched, same fail-closed
posture as native_record_word42/46.

用法: python3 patch_units_ap_dp_mv.py <units.json path> [native_unit_tables.json]
"""
import sys, os, json

sys.path.insert(0, os.path.dirname(__file__))
from export_units import (
    native_ap_for_raw_unit_key,
    native_dp_for_raw_unit_key,
    native_mv_for_raw_unit_key,
)

DEFAULT_NATIVE_TABLES = os.path.join(
    os.path.dirname(__file__), "..", "docs", "data", "exe_tables", "native_unit_tables.json"
)


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 1
    path = argv[1]
    tables_path = argv[2] if len(argv) >= 3 else DEFAULT_NATIVE_TABLES
    tables = json.load(open(tables_path, encoding="utf-8"))

    doc = json.load(open(path, encoding="utf-8"))
    units = doc.get("units", [])

    changed = 0
    skipped = 0
    for u in units:
        raw_unit_key = u.get("portrait")
        lv = u.get("lv")
        if raw_unit_key is None or not lv:
            skipped += 1
            continue
        ap = native_ap_for_raw_unit_key(tables, raw_unit_key, lv)
        dp = native_dp_for_raw_unit_key(tables, raw_unit_key, lv)
        mv = native_mv_for_raw_unit_key(tables, raw_unit_key)
        if ap is None or dp is None or mv is None:
            skipped += 1
            continue
        if u.get("ap") != ap or u.get("dp") != dp or u.get("mv") != mv:
            u["ap"], u["dp"], u["mv"] = ap, dp, mv
            changed += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, separators=(",", ":"))
    print(f"{path}: patched {changed}/{len(units)} units ({skipped} skipped, no native provenance)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
