#!/usr/bin/env python3
"""Surgically patch ap/dp/mv in an already-committed map<N>_units.json in place.

export_units.py's full regeneration also drops native_treasure_event_rules,
native_record_class/race and death_effect/death_reward -- those are populated
by a separate later pipeline step this script does not know about (see
patch_units_hit_ev.py, which exists for the same reason). Re-running
export_units.py wholesale therefore silently regresses already-verified data.
This script instead loads the existing file byte-for-byte, recomputes only
ap/dp/mv via export_units.native_ap_for_raw_unit_key() /
native_dp_for_raw_unit_key() / native_mv_for_raw_unit_key(), and rewrites
just those three keys per unit -- every other key is left untouched.

Formula (full disasm of constructor 0x10d7f..0x10e23, function FUN_00010c50
body 0x10c50..0x11010, 2026-08-31 -- see the three functions' docstrings in
export_units.py for the complete evidence):
  - AP (record +0x37), DP (record +0x39): growth-table-byte * level on the
    high (enemy/friend, raw_unit_key>=0x44) branch, matching the already
    disasm-confirmed HP/MP shape; growth*level + a separate flat base word
    on the lower (persistent-style, raw_unit_key<0x44) branch -- NOT the
    same "+ growth*(level-1)" shape HP/MP's lower branch uses, confirmed
    directly from the pseudocode rather than assumed.
  - MV (record +0x3b): a flat per-(race,cls) value copied verbatim with NO
    level multiplication in either branch. The bug this fixes for MV is not
    missing level-scaling (there is none) but that the existing flat mv
    export came from a race/cls-mismatched table row (see export_units.py's
    PORTRAIT_CLS_NAME comment) rather than the raw-unit-key-indexed table
    the constructor actually reads.

Needs docs/data/exe_tables/native_unit_tables.json (generated by
extract_native_unit_tables.py) for the raw growth-table bytes, keyed by each
unit's own "portrait" field (== raw_unit_key, see export_units.py). Units
without proven native_constructor provenance (raw_unit_key outside the
extracted tables, or lv missing) are left untouched, same fail-closed
posture as native_record_word42/46.

用法: python3 patch_units_ap_dp_mv.py <units.json path> [native_unit_tables.json]
"""
import sys, os, json

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")


def selftest():
    """釘住 doc03 那隻 ch24 LV14 惡魔 —— AP/DP/MV/DX 公式的唯一手算錨點。

    這支工具的目標檔(`remake/assets` 的 mapN_units.json)已於 2026-09-02 隨
    remake/ 移除,所以**寫入側沒有目標可寫**。但它依賴的
    `export_units.native_*_for_raw_unit_key()` 是 2026-08-31 從 constructor
    `FUN_00010c50`(0x10d7f..0x10e23)完整反組譯推導出來的公式,而 doc03 用
    ch24 那隻 LV14 惡魔(`record=[5,26,40,0,5,30,18,6,6,180]`)手算驗過:
    **AP=30×14=420、DP=18×14=252、MV=6(flat)、DX=6×14=84**。

    那組數字是這些公式唯一的獨立錨點。公式一旦被改壞,不會有任何錯誤訊息 ——
    只會讓全部 1818 個單位的數值一起偏掉(當初就是這樣:舊 flat 值與正確值的
    不同比例高達 98%/98%/87%)。所以這裡讓它每次重跑。
    """
    fails = []
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tp = os.path.join(root, "docs", "data", "exe_tables", "native_unit_tables.json")
    if not os.path.isfile(tp):
        print("SKIP: 找不到 native_unit_tables.json")
        return 0
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import export_units as E
    tables = json.load(open(tp, encoding="utf-8"))

    print("(1) 先找出 doc03 那隻惡魔:record 必須唯一命中")
    want = bytes([5, 26, 40, 0, 5, 30, 18, 6, 6, 180]).hex()
    idxs = [r["index"] for r in tables["tables"]["high_class"]["records"]
            if r["bytes_hex"] == want]
    ok1 = len(idxs) == 1
    print(f"    {'PASS' if ok1 else 'FAIL'}: 命中 high_class index {idxs}(應恰好 1 個)")
    if not ok1:
        fails.append(f"錨點 record 命中 {len(idxs)} 筆,無法定位")
        print("\nSELFTEST FAILED:")
        for f in fails:
            print("  -", f)
        return 1
    key = 0x44 + idxs[0]

    print("\n(2) 回歸:LV14 的 AP/DP/MV/DX 必須等於 doc03 的手算值")
    got = {
        "AP": E.native_ap_for_raw_unit_key(tables, key, 14),
        "DP": E.native_dp_for_raw_unit_key(tables, key, 14),
        "MV": E.native_mv_for_raw_unit_key(tables, key),
        "DX": E.native_dx_for_raw_unit_key(tables, key, 14),
    }
    want_vals = {"AP": 420, "DP": 252, "MV": 6, "DX": 84}
    ok2 = got == want_vals
    print(f"    {'PASS' if ok2 else 'FAIL'}: {got}(應 {want_vals})")
    if not ok2:
        fails.append(f"LV14 惡魔的公式輸出與 doc03 不符:{got}")

    print("\n(3) 形狀:AP/DP/DX 隨等級線性成長,MV 不隨等級變(doc03 明載 flat)")
    lin = all(
        E.native_ap_for_raw_unit_key(tables, key, lv) == 30 * lv
        and E.native_dp_for_raw_unit_key(tables, key, lv) == 18 * lv
        and E.native_dx_for_raw_unit_key(tables, key, lv) == 6 * lv
        for lv in (1, 7, 14, 30))
    flat = len({E.native_mv_for_raw_unit_key(tables, key) for _ in range(3)}) == 1
    ok3 = lin and flat
    print(f"    {'PASS' if ok3 else 'FAIL'}: growth×level 成立={lin}、MV 為 flat={flat}")
    if not ok3:
        fails.append("公式形狀不符 doc03(AP/DP/DX 應 growth×level、MV 應 flat)")

    print("\n(4) 非恆真控制:不同單位必須算出不同的值")
    others = [0x44 + r["index"] for r in tables["tables"]["high_class"]["records"][:8]]
    vals = {E.native_ap_for_raw_unit_key(tables, k, 14) for k in others}
    ok4 = len(vals) > 1
    print(f"    {'PASS' if ok4 else 'FAIL'}: 前 8 個單位的 LV14 AP 有 {len(vals)} 種相異值")
    if not ok4:
        fails.append("所有單位算出同一個 AP —— 公式沒有真的查表")

    print("\n(5) 寫入側:目標 mapN_units.json 已隨 remake/ 移除,不在檢查範圍")
    print("    (刻意寫出來,而不是默默略過 —— 見本檔 docstring)")

    if fails:
        print("\nSELFTEST FAILED:")
        for f in fails:
            print("  -", f)
        return 1
    print("\n--selftest passed(錨點定位 + LV14 四值回歸 + 公式形狀 + 非恆真控制)。")
    return 0

sys.path.insert(0, os.path.dirname(__file__))
from export_units import (
    native_ap_for_raw_unit_key,
    native_dp_for_raw_unit_key,
    native_mv_for_raw_unit_key,
)

DEFAULT_NATIVE_TABLES = os.path.join(
    os.path.dirname(__file__), "..", "docs", "data", "exe_tables", "native_unit_tables.json"
)


def main(argv):
    if len(argv) == 2 and argv[1] == '--selftest':
        return selftest()
    if len(argv) < 2:
        print(__doc__)
        return 1
    path = argv[1]
    tables_path = argv[2] if len(argv) >= 3 else DEFAULT_NATIVE_TABLES
    tables = json.load(open(tables_path, encoding="utf-8"))

    doc = json.load(open(path, encoding="utf-8"))
    units = doc.get("units", [])

    changed = 0
    skipped = 0
    for u in units:
        raw_unit_key = u.get("portrait")
        lv = u.get("lv")
        if raw_unit_key is None or not lv:
            skipped += 1
            continue
        ap = native_ap_for_raw_unit_key(tables, raw_unit_key, lv)
        dp = native_dp_for_raw_unit_key(tables, raw_unit_key, lv)
        mv = native_mv_for_raw_unit_key(tables, raw_unit_key)
        if ap is None or dp is None or mv is None:
            skipped += 1
            continue
        if u.get("ap") != ap or u.get("dp") != dp or u.get("mv") != mv:
            u["ap"], u["dp"], u["mv"] = ap, dp, mv
            changed += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, separators=(",", ":"))
    print(f"{path}: patched {changed}/{len(units)} units ({skipped} skipped, no native provenance)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
