#!/usr/bin/env python3
"""Surgically patch hit/ev in an already-committed map<N>_units.json in place.

export_units.py's full regeneration also drops native_treasure_event_rules,
native_record_class/race and death_effect/death_reward — those are populated
by a separate later pipeline step this script does not know about. Re-running
export_units.py wholesale therefore silently regresses already-verified data.
This script instead loads the existing file byte-for-byte, recomputes only
hit/ev via the same formula as export_units.py's hit_ev_for_unit(), and
rewrites just those two keys per unit — every other key is left untouched.

race isn't stored per-unit in the existing JSON schema, so it's re-derived by
re-running parse_field.parse_map() fresh and zipping by index (same FDFIELD
roster order export_units.py originally used to build the file).

base_dx (2026-08-31): prefers native_dx_for_raw_unit_key()'s growth×level DX
(same 0x10d7f..0x10e23 disasm as ap/dp/mv, see export_units.py docstrings),
falling back to the old flat base_stats() dx only when a unit has no proven
native_constructor provenance (raw_unit_key outside the extracted tables, or
lv missing) — same fail-closed posture as patch_units_ap_dp_mv.py. Needs
docs/data/exe_tables/native_unit_tables.json (generated by
extract_native_unit_tables.py) for the raw growth-table bytes, keyed by each
unit's own "portrait" field (== raw_unit_key, see export_units.py).

用法: python3 patch_units_hit_ev.py <extracted/raw> <map_index> <units.json path> [native_unit_tables.json]
"""
import sys, os, json

sys.path.insert(0, os.path.dirname(__file__))
import parse_field
from export_units import base_stats, hit_ev_for_unit, native_dx_for_raw_unit_key, EXE_UNIT, EXE_ITEM

DEFAULT_NATIVE_TABLES = os.path.join(
    os.path.dirname(__file__), "..", "docs", "data", "exe_tables", "native_unit_tables.json"
)


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 1
    raw, m, path = argv[1], int(argv[2]), argv[3]
    tables_path = argv[4] if len(argv) >= 5 else DEFAULT_NATIVE_TABLES
    info = parse_field.parse_map(raw, m)
    exe = json.load(open(EXE_UNIT, encoding="utf-8"))
    items_by_id = {it["id"]: it for it in json.load(open(EXE_ITEM, encoding="utf-8"))}
    native_tables = json.load(open(tables_path, encoding="utf-8")) if os.path.exists(tables_path) else None

    doc = json.load(open(path, encoding="utf-8"))
    src_units = info["units"]
    if len(src_units) != len(doc.get("units", [])):
        print(f"{path}: unit count mismatch ({len(src_units)} vs {len(doc.get('units', []))}), skip", file=sys.stderr)
        return 2

    changed = 0
    for src, dst in zip(src_units, doc["units"]):
        bs = base_stats(exe, src["race"], src["cls"])
        raw_unit_key = dst.get("portrait", src.get("raw_unit_key"))
        lv = dst.get("lv")
        native_dx = native_dx_for_raw_unit_key(native_tables, raw_unit_key, lv) if lv else None
        base_dx = native_dx if native_dx is not None else bs["dx"]
        hit, ev = hit_ev_for_unit(base_dx, dst.get("inventory_slots", []), items_by_id)
        if dst.get("hit") != hit or dst.get("ev") != ev:
            dst["hit"], dst["ev"] = hit, ev
            changed += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, separators=(",", ":"))
    print(f"{path}: patched {changed}/{len(doc['units'])} units")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
